# Generated by Django 6.0.5 on 2026-05-14 11:41

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('fee', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('type', models.CharField(choices=[('CARD_TO_CARD', 'Card To Card'), ('INTERNAL_TRANSFER', 'Internal Transfer'), ('IBAN_TRANSFER', 'IBAN Transfer'), ('CASH_DEPOSIT', 'Cash Deposit'), ('CASH_WITHDRAW', 'Cash Withdraw'), ('LOAN_DISBURSEMENT', 'Loan Disbursement'), ('INSTALLMENT_PAYMENT', 'Installment Payment'), ('LATE_FEE', 'Late Fee'), ('LOAN_SETTLEMENT', 'Loan Settlement'), ('REFUND', 'Refund')], max_length=40)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('BLOCKED', 'Blocked'), ('REVERSED', 'Reversed')], default='PENDING', max_length=20)),
                ('reference_number', models.CharField(max_length=32, unique=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='accounts.account')),
            ],
            options={
                'db_table': 'transactions',
                'ordering': ['-created_at'],
            },
        ),
    ]
