# Generated by Django 6.0.5 on 2026-05-14 22:32

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('duration_months', models.PositiveIntegerField()),
                ('loan_type', models.CharField(choices=[('PERSONAL', 'Personal'), ('HOME', 'Home'), ('CAR', 'Car'), ('BUSINESS', 'Business')], max_length=30)),
                ('monthly_income', models.DecimalField(decimal_places=2, max_digits=18)),
                ('existing_debt', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('UNDER_REVIEW', 'Under Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=30)),
                ('risk_score', models.PositiveIntegerField(default=0)),
                ('manager_note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('principal_amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('interest_rate', models.DecimalField(decimal_places=2, max_digits=6)),
                ('total_payable', models.DecimalField(decimal_places=2, max_digits=18)),
                ('monthly_installment', models.DecimalField(decimal_places=2, max_digits=18)),
                ('duration_months', models.PositiveIntegerField()),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('COMPLETED', 'Completed'), ('DEFAULTED', 'Defaulted'), ('CLOSED', 'Closed')], default='ACTIVE', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('loan_request', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='loans.loanrequest')),
            ],
        ),
    ]
