# Generated by Django 6.0.5 on 2026-05-12 11:57

import apps.authentication.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_remove_session_expires_at_remove_session_last_used_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='expires_at',
            field=models.DateTimeField(default=apps.authentication.models.get_default_session_expiry),
        ),
        migrations.AddField(
            model_name='session',
            name='last_used',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='otpcode',
            name='expires_at',
            field=models.DateTimeField(default=apps.authentication.models.get_expiry_time),
        ),
        migrations.AlterField(
            model_name='session',
            name='access_token',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='session',
            name='refresh_token',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='session',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('revoked', 'Revoked')], default='active', max_length=20),
        ),
        migrations.AlterField(
            model_name='session',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to=settings.AUTH_USER_MODEL),
        ),
    ]
