# Generated by Django 6.0.5 on 2026-05-12 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_session_expires_at_session_last_used_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='device_name',
            field=models.CharField(default='Unknown', max_length=255),
        ),
    ]
